export const currencies = [
  { name: "Доллар США", flag: "us", codeISO: "USD", codeCBR: "R01235" },
  { name: "Евро", flag: "eu", codeISO: "EUR", codeCBR: "R01239" },
  { name: "Фунт стерлингов", flag: "gb", codeISO: "GBP", codeCBR: "R01035" },
  { name: "Японская иена", flag: "jp", codeISO: "JPY", codeCBR: "R01820" },
  { name: "Китайский юань", flag: "cn", codeISO: "CNY", codeCBR: "R01375" },
  { name: "Австралийский доллар", flag: "au", codeISO: "AUD", codeCBR: "R01010" },
  { name: "Канадский доллар", flag: "ca", codeISO: "CAD", codeCBR: "R01350" },
  { name: "Швейцарский франк", flag: "ch", codeISO: "CHF", codeCBR: "R01775" },
  { name: "Гонконгский доллар", flag: "hk", codeISO: "HKD", codeCBR: "R01200" },
  { name: "Сингапурский доллар", flag: "sg", codeISO: "SGD", codeCBR: "R01625" },
  { name: "Шведская крона", flag: "se", codeISO: "SEK", codeCBR: "R01770" },
  { name: "Южнокорейский вон", flag: "kr", codeISO: "KRW", codeCBR: "R01815" },
  { name: "Норвежская крона", flag: "no", codeISO: "NOK", codeCBR: "R01535" },
  { name: "Новозеландский доллар", flag: "nz", codeISO: "NZD", codeCBR: "R1530" },
  { name: "Индийская рупия", flag: "in", codeISO: "INR", codeCBR: "R01270" },
  { name: "Южноафриканский ранд", flag: "za", codeISO: "ZAR", codeCBR: "R01810" },
  { name: "Бразильский реал", flag: "br", codeISO: "BRL", codeCBR: "R01115" },
  { name: "Датская крона", flag: "dk", codeISO: "DKK", codeCBR: "R01215" },
  { name: "Польский злотый", flag: "pl", codeISO: "PLN", codeCBR: "R01565" },
  { name: "Таиландский бат", flag: "th", codeISO: "THB", codeCBR: "R01675" },
];
